# Generated by Django 3.1.2 on 2020-10-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='storage',
            fields=[
                ('storage_id', models.AutoField(primary_key=True, serialize=False)),
                ('storage_link', models.CharField(max_length=50)),
                ('storage_name', models.CharField(max_length=100)),
                ('storage_price', models.CharField(max_length=20)),
            ],
        ),
    ]
