# Generated by Django 3.1.2 on 2020-10-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='storage_link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='storage',
            name='storage_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='storage',
            name='storage_price',
            field=models.CharField(max_length=50),
        ),
    ]
