# Generated by Django 3.1.2 on 2020-11-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('report_serial', models.AutoField(primary_key=True, serialize=False)),
                ('report_id', models.CharField(max_length=50)),
                ('report_link', models.URLField()),
                ('report_name', models.TextField(max_length=255)),
                ('report_num', models.IntegerField(blank=True, default=1, null=True)),
                ('report_price', models.FloatField()),
                ('report_total', models.FloatField(blank=True, null=True)),
                ('report_project', models.TextField(max_length=255)),
            ],
        ),
    ]
