# Generated by Django 3.1.2 on 2020-11-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
