# Generated by Django 3.1.2 on 2020-10-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='commodity',
            fields=[
                ('commodity_serial', models.AutoField(primary_key=True, serialize=False)),
                ('commodity_id', models.CharField(max_length=50)),
                ('commodity_link', models.URLField()),
                ('commodity_name', models.TextField(max_length=255)),
                ('commodity_num', models.IntegerField(blank=True, null=True)),
                ('commodity_price', models.CharField(max_length=50)),
                ('commodity_total', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
