# Generated by Django 3.1.2 on 2020-11-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='commodity_num',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
