# Generated by Django 3.1.2 on 2020-11-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_auto_20201118_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='commodity_num',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
